### ISSUE TITLE
"tapOpensFile: true" will not work if "moveToSharedStorage" or "moveFileToSharedStorage" was used

### ISSUE THREAD

**Issue by MorosophDude** [781flyingdutchman/background_downloader#85] opened 2023-07-11 10:13 UTC
Well I need to move downloaded file to somewhere where user can easily access. It makes sense that `Task` obtained from `taskNotificationTapCallback` doesn't have the new path. So, passing `tapOpensFile: true` didn't work and it logged 
> Failed to open file /data/user/0/com.application_id.my_app/app_flutter/my_directory/downloaded_file.pdf: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.application_id.my_app/app_flutter/my_directory/downloaded_file.pdf

in console when I tapped on a notification.

Since, this package let us registerCallbacks for notification taps I was able to use the recently introduced `pathInSharedStorage` method for a workaround.

For anyone interested / experiencing the same problem here is my workaround.

In main.dart (along with initialization of other services like Firebase, ...)
---
```dart
Future<void> main() async {
    ...

    /// Background Downloader Setup
    FileDownloader().updates.listen(_DownloadClass.callback);
    FileDownloader().configureNotification(
      running: const TaskNotification('Downloading', '{filename}'),
      complete: const TaskNotification('Download completed', '{filename}'),
      progressBar: true,
    );
    FileDownloader().registerCallbacks(
      taskNotificationTapCallback: (task, notificationType) async {
        if (notificationType == NotificationType.complete) {
          final String? newFilePath =
              await FileDownloader().pathInSharedStorage(
            await task.filePath(),
            SharedStorage.downloads,
            directory: "/${FlavorConfig.instance.name}/${task.directory}",
          );

          if (newFilePath != null) {
            FileDownloader().openFile(filePath: newFilePath);
          }
        }
      },
    );

   ...
}

class _DownloadClass {
  static Future<void> callback(TaskUpdate update) async {
    if (update is TaskStatusUpdate) {
      Logger().d(
        'Status update for ${update.task.url} \n New Status: ${update.status}',
      );

      if (update.status == TaskStatus.complete) {
        late final String? newFilePath;
        try {
          newFilePath = await FileDownloader().moveFileToSharedStorage(
            await update.task.filePath(),
            SharedStorage.downloads,
            directory:
                "/${FlavorConfig.instance.name}/${update.task.directory}",
          );
        } catch (e) {
          newFilePath = null;
          Logger().e(e);
        }

        // print("*** file ${newFilePath}");

        if (newFilePath != null) {
          final snackBar = SnackBar(
            content: const Text('Download Successful'),
            backgroundColor: eSuccessColor,
            duration: const Duration(seconds: 10),
            action: SnackBarAction(
              label: "Open",
              backgroundColor: eBackgroundColor,
              textColor: eSuccessColor,
              onPressed: () => FileDownloader().openFile(filePath: newFilePath),
            ),
          );
          final context = _navigatorKey?.currentContext;
          if (context != null) {
            ScaffoldMessenger.of(context).showSnackBar(snackBar);
          }
        }
      }
    } else if (update is TaskProgressUpdate) {
      Logger().d(
        'Progress update for ${update.task.url} \nNew Progress: ${update.progress}',
      );
    }
  }
}
```

In download_file.dart (my helper function for downloading)
---
```dart
downloadFile({
  required String uri,
  String? queryString = '',
  bool sendAuthorization = false,
  required String folderName,
  required String fileName,
  required context,
}) async {
  // Create url using uri and queryString
  // If sendAuthorization is true get tokenAuth, and validate it
  ...

  final task = await DownloadTask(
    url: url,
    directory: folderName, // Passed "folderName" here so that I can use "update.task.directory" in `moveFileToSharedStorage`
    headers: sendAuthorization
        ? {
            'Authorization': tokenAuth,
          }
        : {},
    filename: fileName,
  );
  await FileDownloader().enqueue(task);
}
```

**Comment by 781flyingdutchman** [comment] 2023-07-11 14:17
Yes, that works as intended: `tapOpensFile` is a shortcut that connects the notification directly to its download location, so if you move the file while the notification is still alive it won't work.
Closing this as 'not a bug' but I appreciate your example for others to follow on how to do this!

**Closed** 2023-07-11 14:18 UTC

**Comment by MorosophDude** [comment] 2023-07-11 15:23
Sure. I never intended to report it as a bug. I wanted to document this somewhere so that others (or future me) can find a solution.

BTW, thanks for this awesome package. 👍

**Comment by lazyyq** [comment] 2025-04-08 01:24
Thanks for sharing this, I was just having the same problem!
Does your workaround still work when the filename is duplicate and gets changed to an indexed one during the `moveFileToSharedStorage()` call though?
