### ISSUE TITLE
DownloadTask catches the error, leaving one to unenable to catch it themselves.

### ISSUE THREAD

**Issue by deadlyrazer** [781flyingdutchman/background_downloader#166] opened 2023-10-12 11:21 UTC
If there's no connection to the server and DownloadTask throws a SocketException, it can't be caught by the try catch block because it's being caught inside and not being rethrown.

Another issue is that the TaskStatusUpdate of `.enqueue` is `.running` not failed after using a DownloadTask that threw a SocketException and then takes it takes time **again** to make its state `TaskStatus.failed`.

Lastly, the requestTimeout in .configure should work for DownloadTask as well because right now the timeout timing is huge.
```dart  await FileDownloader().configure(
    globalConfig: [
      (Config.requestTimeout, const Duration(seconds: 3)),
    ],

**Comment by 781flyingdutchman** [comment] 2023-10-12 13:11
Hi, thanks for reaching out. Per the issue template, can you tell me the platform (eg Android, iOS), platform version and plugin version you're encountering this? Can you also explain what the result is that you expect, versus the result that you get (because that's not clear from your description), can you add logs and a code snippet you used that reproduces the error and finally can you file separate bugs for separate issues, using the issue template? Thanks!

**Comment by 781flyingdutchman** [comment] 2023-10-13 16:16
I think you captured this in #167 (and while I've closed that issue I do have a suggestion for how to solve it that I'd like your input on), so I am going to close this issue. Thanks for your input!

**Closed by 781flyingdutchman** 2023-10-13 16:16 UTC
