### ISSUE TITLE
Android Download not working: Task ensued and running then stay at 0%

### ISSUE THREAD

**Issue by SamuelMTDavies** [781flyingdutchman/background_downloader#159] opened 2023-10-06 09:56 UTC
**Describe the bug**
File downloads on android do not start and complete as they should.

**To Reproduce**
Steps to reproduce the behaviour:
Can aim to supply minimum reproducible example at a later time if necessary.

**Expected behaviour**
File should download and then on completion open.

**Logs**
These logs relate to the code in Code Snippet 1.
```
I/flutter (17374): Start download file from internet!
I/flutter (17374): Download files
I/flutter (17374): /data/user/0/{package}/app_flutter/{PDF_NAME}.pdf
I/flutter (17374): Status: TaskStatus.enqueued
I/flutter (17374): Status: TaskStatus.running
I/flutter (17374): Progress: 0.0%
```

**Code**
Two code snippets that I have tried both work on iOS and both fail on android.

**Code Snippet 1:**
```
onPressed: () async {
                  final task = await DownloadTask(
                    url: property.documents?[index].attachmentUrl ?? "",
                  ).withSuggestedFilename(unique: true);

                  // Start download, and wait for result. Show progress and status changes while downloading
                  final result = await FileDownloader().download(task,
                      onProgress: (progress) =>
                          print('Progress: ${progress * 100}%'),
                      onStatus: (status) => print('Status: $status'));

                  // Act on the result
                  switch (result.status) {
                    case TaskStatus.complete:
                      print('Success!');
                      FileDownloader().openFile(task: task);
                      break;

                    case TaskStatus.canceled:
                      print('Download was canceled');
                      break;

                    case TaskStatus.paused:
                      print('Download was paused');
                      break;

                    default:
                      print('Download not successful');
                  }
                },
```

**Code Snippet 2:**
```
onPressed: () async {
                  final task = await DownloadTask(
                    url: property.documents?[index].attachmentUrl ?? "",
                  ).withSuggestedFilename(unique: true);
                  
                  await FileDownloader()
                      .configureNotification(
                          tapOpensFile: true,
                          running: TaskNotification(
                              'Downloading', 'file: {filename}'),
                          progressBar: true)
                      .download(task);

                  await FileDownloader().openFile(task: task);
                },
```

**Additional context**
Works as expected on iOS

**Comment by SamuelMTDavies** [comment] 2023-10-06 10:09
Running it with a more verbose logging I get the following:

```
I/BackgroundDownloader(19977): Enqueuing task with id 845865197
D/EGL_emulation(19977): app_time_stats: avg=28.01ms min=1.69ms max=751.86ms count=33
D/CompatibilityChangeReporter(19977): Compat change id reported: 194532703; UID 10179; state: ENABLED
I/TaskWorker(19977): Starting task with taskId 845865197
I/TaskWorker(19977): Not using proxy for any task
E/WM-WorkerWrapper(19977): Work [ id=4be547bb-fb25-4d7e-ad26-3772aea3476d, tags={ com.bbflight.background_downloader.DownloadTaskWorker, BackgroundDownloader, taskId=845865197, group=await } ] failed because it threw an exception/error
[        ] E/WM-WorkerWrapper(19977): java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfUrlConnection;
[        ] E/WM-WorkerWrapper(19977): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
[        ] E/WM-WorkerWrapper(19977): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
[        ] E/WM-WorkerWrapper(19977): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
[        ] E/WM-WorkerWrapper(19977): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
[        ] E/WM-WorkerWrapper(19977): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[        ] E/WM-WorkerWrapper(19977): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[        ] E/WM-WorkerWrapper(19977): 	at java.lang.Thread.run(Thread.java:1012)
[        ] E/WM-WorkerWrapper(19977): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfUrlConnection;
[        ] E/WM-WorkerWrapper(19977): 	at com.bbflight.background_downloader.TaskWorker$doTask$2.invokeSuspend(TaskWorker.kt:481)
[        ] E/WM-WorkerWrapper(19977): 	at com.bbflight.background_downloader.TaskWorker$doTask$2.invoke(Unknown Source:8)
[        ] E/WM-WorkerWrapper(19977): 	at com.bbflight.background_downloader.TaskWorker$doTask$2.invoke(Unknown Source:4)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
[        ] E/WM-WorkerWrapper(19977): 	at com.bbflight.background_downloader.TaskWorker.doTask(TaskWorker.kt:480)
[        ] E/WM-WorkerWrapper(19977): 	at com.bbflight.background_downloader.TaskWorker.access$doTask(TaskWorker.kt:50)
[        ] E/WM-WorkerWrapper(19977): 	at com.bbflight.background_downloader.TaskWorker$doWork$2.invokeSuspend(TaskWorker.kt:428)
[        ] E/WM-WorkerWrapper(19977): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
[        ] E/WM-WorkerWrapper(19977): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
[        ] E/WM-WorkerWrapper(19977): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[        ] E/WM-WorkerWrapper(19977): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.network.FirebasePerfUrlConnection" on path: DexPathList[[zip file "/data/app/~~xSspVFFehixkpKzXmcIqdw==/{PACKAGE}-xNY7AclvDbI-j1yzi574Mg==/base.apk"],nativeLibraryDirectories=[/data/app/~~xSspVFFehixkpKzXmcIqdw==/{PACKAGE}-xNY7AclvDbI-j1yzi574Mg==/lib/arm64, /data/app/~~xSspVFFehixkpKzXmcIqdw==/{PACKAGE}-xNY7AclvDbI-j1yzi574Mg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
[        ] E/WM-WorkerWrapper(19977): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
[        ] E/WM-WorkerWrapper(19977): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[        ] E/WM-WorkerWrapper(19977): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[        ] E/WM-WorkerWrapper(19977): 	... 20 more
[        ] I/WM-WorkerWrapper(19977): Worker result FAILURE for Work [ id=4be547bb-fb25-4d7e-ad26-3772aea3476d, tags={ com.bbflight.background_downloader.DownloadTaskWorker, BackgroundDownloader, taskId=845865197, group=await } ]
[ +112 ms] D/CompatibilityChangeReporter(19977): Compat change id reported: 78294732; UID 10179; state: ENABLED
```

**Comment by 781flyingdutchman** [comment] 2023-10-06 10:37
Thanks for sharing. The cause "Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfUrlConnection;" suggests this is related to firebase

**Comment by SamuelMTDavies** [comment] 2023-10-06 11:05
I'm not sure it's that simple. I only have analytics and crashlytics installed - I wonder if it's mentioning it as it's crashed. Effect rather than cause. That part of my app has no dependencies or interactions with Firebase for anything.


Any thoughts? I am looking at that angle and not discounting it but surely others use your plugin with firebase dependencies - Surely if it was firebase they would be having issues too?

**Comment by SamuelMTDavies** [comment] 2023-10-06 11:20
Ok so i've done some tweaks and digging: The issue was being obscured by some sort of old dependency on Firebase Performance package.
```
I/WM-WorkerWrapper(32669): Worker result SUCCESS for Work [ id=48f98fd5-5b00-435e-819c-f5e3e6968ef0, tags={ com.bbflight.background_downloader.DownloadTaskWorker, BackgroundDownloader, taskId=2228566878, group=await } ]
I/BackgroundDownloader(32669): Failed to open file /data/user/0/{PACKAGE}/app_flutter/test.pdf: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/{PACKAGE}/app_flutter/test.pdf
```

The issue is to do with the directory? I haven't specified any directory so this is failing on the default?

**Comment by 781flyingdutchman** [comment] 2023-10-06 22:08
Hi, can you let me know what Android version you are using, and describe exactly what you are doing when this error happens? For example, I am a bit confused about having both `tapOpensFile: true` and an explicit call to `openFile`.

The error you list is related to the `FileProvider` that translates paths into URIs on newer platforms. It is possible that the FileProvider configured in the background_downloader conflicts with one defined in your app. In your app's Manifest, do you have any references that look like this (this is the example from the downloader, yours would look similar but have different values):
```
        <provider
            android:name="com.bbflight.background_downloader.OpenFileProvider"
            android:authorities="${applicationId}.com.bbflight.background_downloader.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/bgd_file_paths" />
        </provider>
```
or, do you have anywhere in your `res/xml` directory an xml file that looks like this:
```
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="external-path"
        path="."/>
    <external-cache-path
        name="external-cache-path"
        path="."/>
    <external-files-path
        name="external-files-path"
        path="."/>
    <files-path
        name="files_path"
        path="."/>
    <cache-path
        name="cache-path"
        path="."/>
    <external-media-path
        name="external_media"
        path="." />
</paths>
```

If so, I think the issue may be there - try removing 'your' references to file provider and see if it works then?

**Comment by SamuelMTDavies** [comment] 2023-10-09 08:50
Android Version: EMUI12 which I believe is ~ Android 11
Device: Huawei Mate 20 Pro


We just have a button that when the user clicks on it triggers the download and should open it for them to see. I have probably put it in twice as I wasn't getting the expected behaviour.

Nothing like this in my manifest

```
        <provider
            android:name="com.bbflight.background_downloader.OpenFileProvider"
            android:authorities="${applicationId}.com.bbflight.background_downloader.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/bgd_file_paths" />
        </provider>
```


and no xml file either.


I am going to try the temp directory option, I wonder if it's due to the EMUI OS but the behaviour is the same on the simulator.

 
Would this intent interfere with your package in anyway?

```
 <intent>
            <action android:name="android.intent.action.VIEW" />
            <!-- If you don't know the MIME type in advance, set "mimeType" to "*/*". -->
            <data android:mimeType="application/pdf" />
        </intent>
```

**Comment by 781flyingdutchman** [comment] 2023-10-09 10:09
Also, do you run into the same issue if you test in a submission or device with a standard Android OS?

**Comment by SamuelMTDavies** [comment] 2023-10-09 10:31
Example app works as expected with the file opening: 

```
Successfully downloaded taskId 2898004930 to /data/user/0/com.bbflight.background_downloader_example/files/dog.jpg
```

Only difference I can see is that the path is '/files/' in the example app and in mine it's '/app_flutter/'?

**Comment by SamuelMTDavies** [comment] 2023-10-09 10:32
> Also, do you run into the same issue if you test in a submission or device with a standard Android OS?

I will try find a real device to do this on but in testing I was using a simulated Pixel device.

**Comment by SamuelMTDavies** [comment] 2023-10-09 10:42
Ok so I have resolved this by adding the following:

`baseDirectory: BaseDirectory.applicationSupport` and removing the `tapOpensFile: true`

I'm not sure why this makes the difference but happy to continue to explore the issue and help make the package more robust if that is indeed the issue on not just user error on my part.

Just about to test iOS to make sure that is still working as expected.

**Comment by VivekkumarRaiDO** [comment] 2023-10-09 10:52
what to pass in  directory i want to download my pdf file in download folder in android device .

This is my code
directory: 'Downloads',
baseDirectory: BaseDirectory.applicationSupport,

**Comment by ranjanSoumyaDO** [comment] 2023-10-09 10:55
@VivekkumarRaiDO  I am facing the same issue. @SamuelMTDavies What did you pass in your directory

**Comment by SamuelMTDavies** [comment] 2023-10-09 11:05
> @VivekkumarRaiDO I am facing the same issue. @SamuelMTDavies What did you pass in your directory

Just try by passing baseDirectory: BaseDirectory.applicationSupport when setting up the task.

**Comment by ranjanSoumyaDO** [comment] 2023-10-09 11:07
@SamuelMTDavies can we change the path? I am not able to see it in the android file.

**Comment by SamuelMTDavies** [comment] 2023-10-09 11:07
> what to pass in directory i want to download my pdf file in download folder in android device .
> 
> This is my code directory: 'Downloads', baseDirectory: BaseDirectory.applicationSupport,
> 
> Please replay ASAP

I think it's not possible to select the download folder on android. As per the ([path_provider documentation](https://pub.dev/packages/path_provider)). Im not sure but either don't save the document there or put it in temporary folder and let the user save it to the downloads. (Admittedly I've not done or tested this option but it's something I've considered trying to resolve this issue.)

**Comment by SamuelMTDavies** [comment] 2023-10-09 11:10
> @SamuelMTDavies can we change the path? I am not able to see it in the android file.

Use a combination of the **directory** and **base path** as per this example in the README.

```
final task = DownloadTask(
        url: 'https://google.com',
        filename: 'testfile.txt',
        **directory: 'my/subdir',**
        **baseDirectory: BaseDirectory.temporary);**
```

**Comment by ranjanSoumyaDO** [comment] 2023-10-09 11:14
@SamuelMTDavies  its storing like /data/user/0/com.forwardair.staging.forwardten4/cache/my/subdir/2023-Q1-17425-tmstp.pdf its hard to find in file explorer .

**Comment by 781flyingdutchman** [comment] 2023-10-09 11:33
@SamuelMTDavies on the `baseDirectory`: for some reason, if you select `.applicationDocuments` as your base directory, the file cannot be opened using tap or `openFile`. Any other choice of `baseDirectory` works,  e.g. `.applicationSupport`, which is what the dog picture is using in the example. It's listed in the [documentation](https://github.com/781flyingdutchman/background_downloader#opening-a-downloaded-file), but it's annoying, so if anyone knows why it doesn't work for that directory, and how to fix it, please let me know!

**Comment by 781flyingdutchman** [comment] 2023-10-09 11:36
@ranjanSoumyaDO if you want the file to show in the Downloads directory, then you have to download it first to one of the `BaseDirectory` entries, the call `FileDownloader().moveToSharedStorage(task, SharedStorage.downloads)` to move it there. See discussion #163 for potential future ways to do this more directly

**Comment by 781flyingdutchman** [comment] 2023-10-09 11:37
Closing this issue as the original issue appears to have been resolved

**Closed by 781flyingdutchman** 2023-10-09 11:37 UTC

**Comment by SamuelMTDavies** [comment] 2023-10-09 11:54
> @SamuelMTDavies on the `baseDirectory`: for some reason, if you select `.applicationDocuments` as your base directory, the file cannot be opened using tap or `openFile`. Any other choice of `baseDirectory` works, e.g. `.applicationSupport`, which is what the dog picture is using in the example. It's listed in the [documentation](https://github.com/781flyingdutchman/background_downloader#opening-a-downloaded-file), but it's annoying, so if anyone knows why it doesn't work for that directory, and how to fix it, please let me know!

I will have a look and see but the current solution is fine for my use case.

**Comment by ranjanSoumyaDO** [comment] 2023-10-09 12:03
@SamuelMTDavies  it works thanks
